// <auto-generated />
using Fab.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fab.Core.Migrations
{
    [DbContext(typeof(CmsWorkingDbContext))]
    [Migration("20260415164433_AddHeadingLinkDivider")]
    partial class AddHeadingLinkDivider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Fab.Data.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Fab.Data.ContentBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ContentBases", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Fab.Data.OrderedContentEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ContentId");

                    b.ToTable("OrderedContentEntry");
                });

            modelBuilder.Entity("Fab.Data.Image", b =>
                {
                    b.HasBaseType("Fab.Data.ContentBase");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Fab.Data.Paragraph", b =>
                {
                    b.HasBaseType("Fab.Data.ContentBase");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Paragraphs", (string)null);
                });

            modelBuilder.Entity("Fab.Data.OrderedContentEntry", b =>
                {
                    b.HasOne("Fab.Data.Article", null)
                        .WithMany("Entries")
                        .HasForeignKey("ArticleId");

                    b.HasOne("Fab.Data.ContentBase", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Fab.Data.Image", b =>
                {
                    b.HasOne("Fab.Data.ContentBase", null)
                        .WithOne()
                        .HasForeignKey("Fab.Data.Image", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fab.Data.Paragraph", b =>
                {
                    b.HasOne("Fab.Data.ContentBase", null)
                        .WithOne()
                        .HasForeignKey("Fab.Data.Paragraph", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fab.Data.Article", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
