<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fab.Core\Fab.Core.csproj" />
    <ProjectReference Include="..\Fab.Data\Fab.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="fab.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Edit\ArticleEditTest.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Edit\EditListView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Edit\EditTextView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
